name: Build and deploy Python app to Azure Web App - sistema-rh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instalar dependências e build do frontend
      - name: Install and build frontend
        run: |         
          npm install
          npm run build

      # Build do backend (Flask)
      - name: Install backend dependencies
        run: |
          cd backend/api
          pip install -r requirements.txt

      # Zip o projeto para deploy
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_47EB5C4992B342B3839856B2A54757B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7EA499247C744D8A5FA777122BDBE9B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C704665F769A4FD3ADBAF9938D74151B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sistema-rh'
          slot-name: 'Production'
